### PR TITLE
change nginx binary

### PR DESCRIPTION
**Pull request by neerfri**
Hi, If you're interested, this PR adds the following changes
- upgrade to openresty 1.7.10.1
- upgrade to pcre 8.37
- add --with-http_stub_status_module to nginx compilation

### CODE REVIEW

**Comment by mathieujobin** [comment]
this looks good. does it work with lapis on heroku ?

could you also generate the openresty 1.9 rockspec?

**Comment by mrrobby** [comment]
@mathieujobin @neerfri did you ever get something going to get this on luarocks?  I think we should fork this and keep it updated.

**Comment by mathieujobin** [comment]
i did succeed deploying a small app to heroku, if that's the question.
but I totally gave up on the whole lua/moonscript thing.
community is too small, and it took months before someone noticed anything I tried...

I'm switching everything to elixir/phoenix now

**Comment by mathieujobin** [comment]
come on, this long lasting PR was open in june 2015

**Comment by mrrobby** [comment]
Sorry about that @mathieujobin.  @leafo do you have plans to maintain this any longer?  I see there's been a [fork that's gotten some attention at least last year](https://github.com/applicaster/heroku-openresty).  Should we work with that instead?  It would help to set on a maintained repo we use to start publishing through [OPM](http://opm.openresty.org) as it grows.  Thoughts?

**Comment by mathieujobin** [comment]
I don't remember clearly. but I think what I had deployed is this branch

https://github.com/leafo/heroku-openresty/compare/master...mathieujobin:1_9_3_testing

which includes the commit from this PR

**Comment by mrrobby** [comment]
thanks @mathieujobin, that's a helpful link

**Pull request closed without merging**
